[faults]
fifo_path="/tmp/faults.fifo"
#fifo_path_completed="/tmp/faults_completed.fifo"
[cache]
apply_eviction=false
[cache.simple]
custom_size="1gb"
blocks_per_page=1
# [cache.manual]
# io_block_size=4096
# page_size=4096
# no_pages=10
[filesystem]
log_all_operations=true
logfile=""

#[[injection]]
#type="torn-seq"
#op="write"
#file="/home/gsd/lfs-test/data-r/f1.txt"
#persist=[2]
#occurrence=1

[[injection]]
type="torn-op"
file="/home/gsd/lfs-test/data-r/f1.txt"
persist=[2]
parts=2
occurrence=1