[faults]
fifo_path="/tmp/faults.fifo"
#fifo_path_completed="/tmp/faults_completed.fifo"
[cache]
apply_eviction=false
[cache.simple]
custom_size="1gb"
blocks_per_page=1
# [cache.manual]
# io_block_size=4096
# page_size=4096
# no_pages=10
[filesystem]
log_all_operations=true
logfile=""
[[injection]]
type="clear-page"
from="/home/marta/lazyfs/root/ex.txt"
timing="after"
op="write"
occurrence=999
pages="first"
return=true

# /home/marta/lazyfs/root/ex.txt
